
img_battle_start = "battle/battle_start.png"
img_battle_win = "battle/battle_win.png"
img_battle_lose = "battle/battle_lose.png"
img_drop = "battle/drop.png"
img_tire = "battle/tire.png"
img_tire_3 = "battle/tire_3.png"
img_capture_item = "battle/capture_item.png"
img_capture_success = "battle/capture_success.png"
img_pet_2 = "battle/two.png"
img_heal_two = "battle/heal_two.png"
img_reload = "battle/reload.png"
img_klose_layer_2 = "battle/klose_layer_2.png"
img_my_turn = "battle/my_turn.png"
img_not_my_turn = "battle/not_my_turn.png"
